sudo: false

language: c
cache: ccache

env:
  - KVER=3.16
  - KVER=3.17
  - KVER=3.18
  - KVER=3.19
  - KVER=4.0
  - KVER=4.1
  - KVER=4.2
  - KVER=4.3
  - KVER=4.4
  - KVER=4.5
  - KVER=4.6
  - KVER=4.7
  - KVER=4.8
  - KVER=4.9
  - KVER=4.10
  - KVER=4.11
  - KVER=4.12
  - KVER=4.13
  - KVER=4.14
  - KVER=4.15
  - KVER=4.16
  - KVER=4.17
  - KVER=master

matrix:
  allow_failures:
    - env: KVER=master
  include:
    - env: StyleCheck
      script: ./ci/run_style_check

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - bc
      - g++-4.8
      - libelf-dev

script:
  - CC=gcc-4.8 ./ci/build_against_kernel ${KVER}
